config/routes.rb
Pm::Application.routes.draw do
 resources :projects do
   resources :teams
 end
 resources :people

   root :to => 'projects#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
has_many :teams
has_many :projects, :through=>:teams

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name,  :presence => true
  validates :client, :presence => true
  validates :cost,  :presence => true
  validates :starting_date, :presence => true
  validates :ending_date,  :presence => true
  has_one :team
  has_many :persons, :through => :team

end

app/models/team.rb
class Team < ActiveRecord::Base
belongs_to :project
has_many :people
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
  @people = Person.all
  end

  def edit
  @person = Person.find(params[:id])
  end

  def new
  @person =Person.new()
  end

  def create
  @person = Person.new(params[:person])
  @person.save!
  redirect_to (people_path)
  end

  def destroy
   @person = Person.find(params[:id])
  @person.destroy
  redirect_to (people_path)
  end

  def show
  @person = Person.find(params[:id])
  end

  def update
  @person = Person.find(params[:id])
  @person.save!
  @person.update_attributes(params[:person])
  redirect_to (people_path)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  @projects = Project.all
  end

  def edit
  @project = Project.find(params[:id])
  end

  def new
  @project =Project.new()
  end

  def create
  @project = Project.new(params[:project])
  @project.save!
  redirect_to (projects_path)
  end

  def show
  @project = Project.find(params[:id])
  end

  def update
  @project = Project.find(params[:id])
  @project.save!
  @project.update_attributes(params[:project])
  redirect_to (projects_path)
  end

  def destroy
  @project = Project.find(params[:id])
  @project.destroy
  redirect_to (projects_path)
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  @project = Project.find(params[:project_id])
  end

  def edit
  @project = Project.find(params[:project_id])
  @team = Team.find(params[:id])
  @people = Person.all
  end

  def show
  @team = Team.find(params[:id])
  end

  def new
  @team =Team.new()
  @project=Project.find(params[:project_id])
  @people = Person.all
  end

  def update
  @team = Team.find(params[:id])
  @team.update_attributes(params[:team])
  @team.save!
  redirect_to projects_path
  end

  def destroy
  @team = Team.find(params[:id])
  @team.destroy
  redirect_to (teams_path)
  end

  def create
    project = Project.find(params[:project_id])       #find the project to assign the team to
    @team = project.build_team()                       #initialise new team for the team (new does not create in database)
    people_hash = params[:team]                       #capture the parameters passed from the form(persons)
    people_id_array = people_hash.values              #create an array of the ids of the persons hash captured to be assigned to the team
    people_id_array.each do |id|                      # loop through the array of the person ids
      person = Person.find(id)                        # find each person from the looped id
      @team.people << person                          # Assign the person to the team
    end
    @team.save!                                       # Save the team actually to the database
    project.team_id = @team.id                        # assign team id to project id
    project.save!                                     # save the project as well
    redirect_to projects_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pm</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
</head>
<body >
<h1>Project Management</h1>


<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= semantic_form_for @person do |f| %>
    <%= f.inputs %>
    <%= f.buttons %>

  <% end %>

app/views/people/_listing.html.erb
<table>
  <tr>
    <th>Employee Name</th>
    <th>Address</th>
    <th>Phone No</th>
    <th>Email</th>
    <th>Speciality</th>
    <th></th>
    <th></th>
  </tr>
<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.address %></td>
    <td><%= person.phone_no %></td>
    <td><%= person.email %></td>
    <td><%= person.speciality %></td>

    <td><%= link_to "Edit", edit_person_path(person.id) %></td>
    <td><%= link_to "Delete", person, :confirm=>"Are You Sure?", :method=> :delete %></td>
  </tr>
<% end %>
</table>
<br />

app/views/people/create.html.erb
<h1>Persons#create</h1>
<p>Find me in app/views/persons/create.html.erb</p>

app/views/people/destroy.html.erb
<h1>Persons#destroy</h1>
<p>Find me in app/views/persons/destroy.html.erb</p>

app/views/people/edit.html.erb
<%= render "form" %>
<%= link_to "Back", people_path %>

app/views/people/index.html.erb
<%= render"listing" %>
<%= link_to 'Add Person', new_person_path %>
<br />
<%= link_to 'Back' , projects_path %>

app/views/people/new.html.erb
<%= render'form'%>
<%= link_to "back", people_path %>

app/views/people/show.html.erb
<h1>Persons#show</h1>
<p>Find me in app/views/persons/show.html.erb</p>

app/views/people/update.html.erb
<h1>Persons#update</h1>
<p>Find me in app/views/persons/update.html.erb</p>

app/views/projects/_form.html.erb
<%= semantic_form_for @project do |f| %>

    <%= f.inputs :name %>
    <%= f.inputs :client %>
    <%= f.inputs :cost %>
    <%= f.inputs :starting_date %>
    <%= f.inputs :ending_date %>

    <%= f.buttons %>

  <% end %>

app/views/projects/_listing.html.erb
<table>
  <tr>
    <th>Project Name</th>
    <th>client</th>
    <th>Cost</th>
    <th>Starting Date</th>
    <th>Ending Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.client %></td>
    <td><%= project.cost %></td>
    <td><%= project.starting_date %></td>
    <td><%= project.ending_date %></td>
    <td>

    <%if project.team.nil?%>
      <%= link_to "Assign Team", new_project_team_path(project.id) %>
    <% else  %>
      <%= link_to "Team", project_teams_path(project.id) %>
    <% end %>

    </td>
    <td><%= link_to "Edit", edit_project_path(project.id) %></td>
    <td><%= link_to "Delete", project, :confirm=>"Are You Sure?", :method=> :delete %></td>
  </tr>
<% end %>
</table>
<br />

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<%= render "form" %>
<%= link_to "Back", people_path %>

app/views/projects/index.html.erb
<%= render"listing"%>
<%= link_to 'New project', new_project_path %>
<br />
<%= link_to "Employee Detail", people_path %>

app/views/projects/new.html.erb
<%= render'form'%>

<%= link_to "back", projects_path %>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>